### ISSUE TITLE
All times are in UTC, not local

### ISSUE THREAD

**Issue by thislooksfun** [elitau/spotthestation#1]
When subscribing to a calendar via spotthestation.ede.li, the times are always at utc+0, not the local time. I know iCal has support for time zones, but I don't know enough Elixir to open a PR.

**Comment by elitau** [comment]
How would pass in the Timezone? Via Param? Or is there some kind of (iCal) standard?

**Comment by thislooksfun** [comment]
Well the issue is that this service is reading in the time from NASA, which is in local time, then parsing it as if it were UTC. So if, for instance, you look at the NASA feed for [Seattle, Washington, U.S.](https://spotthestation.nasa.gov/sightings/indexrss.cfm?country=United_States&region=Washington&city=Seattle) (which is currently GMT-8), it says that there is a sighting on Nov 24, 2021 at 6:05pm. Looking at the same event in the [generated iCal feed](http://spotthestation.ede.li/for_city?country=United_States&region=Washington&city=Seattle) also says that it's at 6:05pm... GMT. Which shows up on the calendar at 10:05am local time.

Doing some research into the [iCal date time specification](https://www.kanzaki.com/docs/ical/dateTime.html), it seems that the reason for this is that you are just blindly parsing the date time strings and appending 'Z', which is interpreted as `Form #2: Date with UTC Time`.

The cheap fix is to just not append the 'Z', which will then be interpreted as `Form #1: Date with Local Time`. This will work in most cases, as users will spend most of their time in the same timezone, though it can still be wrong (though in a different way) if/when the user travels.

The *ideal* (but much more involved) fix is to determine the time zone from the parameters, then prepend a `TZID` (with a corresponding [`VTIMEZONE` block](https://www.kanzaki.com/docs/ical/vtimezone.html)), as per `Form #3: Date with Local Time and Time Zone Reference`. This would then always show the correct adjusted time, but has the obvious downside of requiring some sort of time zone lookup.

**Comment by elitau** [comment]
Thanks for the groundwork!

I've implemented the cheap fix and released the updated version. Is it working as expected?

**Comment by thislooksfun** [comment]
It seems to be working as expected!
